### ISSUE TITLE
de.json - "Erleben" not the best translation in this context

### ISSUE THREAD

**Issue by Soraldor** [instatushq/languages#100]
"Erleben" is maybe not the best translation in these cases. Some improvements imho: 

- "experiencingMajorOutage": "Erleben Sie einen größeren Ausfall", -> "Größeren Ausfall festgestellt"
- "experiencingPartialOutage": "Teilausfall erleben", -> "Teilausfall festgestellt"
- "experiencingDegradedPerformance": "Leistungsabfall erleben", -> "Leistungsabfall festgestellt"
- "experiencingMinorOutage": "Kleinere Ausfälle erleben", -> "Kleinere Ausfälle festgestellt"
- "experiencingPartiallyDegradedPerformance": "Erleben einer teilweise herabgesetzten Leistung", -> "Teilweise herabgesetzte Leistung festgestellt"

"Erleben" sounds a little to funny here.

**Comment by alisalahio** [comment]
Thank youu just updated these :D
