### ISSUE TITLE
Latest widget code has invalid JavaScript code

### ISSUE THREAD

**Issue by MathiasWP** [instatushq/languages#126]
Note sure where to post this, our the script-src for our instatus widget is triggering a lot of errors in our monitoring. It's caused by this line of code:

<img width="740" alt="Screenshot 2024-03-13 at 23 05 25" src="https://github.com/instatushq/languages/assets/48158184/987c545b-983f-44cf-9341-558d296f1560">

It seems like the widget id is missing string quotes, so the browser reads it as invalid Regex

**Comment by ahmedhatem777** [comment]
Hey Mathias,
Thanks for letting us know and sorry about that.
We've released a fix for this issue.
Please let us know if you're still seeing it or if you need any help.
Also, please direct all of your issues and concerns to our support email (support@instatus.com) for better and faster communication.
