### ISSUE TITLE
Is it possible to translate "Resolved after:" time text?

### ISSUE THREAD

**Issue by bark1n9** [instatushq/languages#33]
Could not find it in JSONs.

Example image: https://ibb.co/vkt5rkj

**Comment by alisalahio** [comment]
Yeah sure, which language is it missing in?

**Comment by bark1n9** [comment]
Turkish

**Comment by alisalahio** [comment]
I found it at "resolvedAfter"

**Comment by bark1n9** [comment]
I'm not talking about the resolved After text, I was trying to translate the text next to it that says "about 1 hour"

**Comment by alisalahio** [comment]
I found out this is due using the wrong Turkish locale. 
I fixed it in this commit.. https://github.com/instatushq/languages/commit/8737fdb04f19a778fc2e75e64877e908bc9c31da
Would you please confirm that it works now?

**Comment by bark1n9** [comment]
Yes! It seems to be fixed. Thank you so much!
