### ISSUE TITLE
Page title not translated

### ISSUE THREAD

**Issue by coder-bts** [instatushq/languages#47]
The page title still contains the phrase "Status" regardless the translation

**Comment by alisalahio** [comment]
Hi @coder-bts I fixed this, but it's not yet shipped to everyone. I'll close this but please let me know your status page URL if you want to receive the fix :D

**Comment by coder-bts** [comment]
Hi Sure, bitznet.instatus.com

Best,
Chihao (Bill) Huang

**Comment by alisalahio** [comment]
Hi @coder-bts,

I shipped the update to your page :D

**Comment by coder-bts** [comment]
Great! It works perfectly.

Best,
Chihao (Bill) Huang
