### ISSUE TITLE
Finnish: Resolved after [time] minutes can't be translated perfectly to Finnish language

### ISSUE THREAD

**Issue by GhostSlayer** [instatushq/languages#69]
hey, i'm trying to translate "Resolved after [time]" to Finnish language, but it can't be translated perfectly.

The current translation is "Ratkaistu [time] minuuttia" which translates to "Resolved [time] minutes". since Finnish is a complicated language, I need to get text after "[time]" which would be like "Ratkaistu [time] minuutin jälkeen", and which would translate to "Resolved after [time]" and it would be perfect. Can you help fixing that
![image](https://user-images.githubusercontent.com/51095261/139425435-fda30daa-9772-4528-8059-9e2af127d379.png)

**Comment by alisalahio** [comment]
@CCKNBC `unsubscribeNotice` is used in SMS like:

Reminder: you can unsubscribe from alerts like these at [unsubscribe-url]
