### ISSUE TITLE
Context issue in Dutch translation

### ISSUE THREAD

**Issue by fkoning-sp** [instatushq/languages#84]
When browsing notice history you will see "Notice history" in the browser title bar and the header:

![image](https://user-images.githubusercontent.com/39669126/163948362-288f2b7b-fbdd-474c-93fb-8406a7c004ec.png)

The Dutch translation should be 'Berichtgeschiedenis' instead of 'Let op geschiedenis'

![image](https://user-images.githubusercontent.com/39669126/163949573-cc8438d6-abfc-4f65-a4ad-cceaf19be62e.png)

**Comment by alisalahio** [comment]
Thank you!!
