### ISSUE TITLE
Incorrect Dutch translation of `update` depending on context

### ISSUE THREAD

**Issue by lucasvdh** [instatushq/languages#97]
The Dutch (NL) translation currently used for the key `update` is not correct in every situation.

In Dutch there's a clear distinction between _"an update about something"_ and _"to update something"_.

- _"an update about something"_ translates to "Update"
- _"to update something"_ translates to "Bijwerken"

An incorrect translation is currently being used in the incident update timeline overview, because in this context `update` means _"an update about something"_ and not _"to update something"_. This is why "Update" would be the correct Dutch translation in this context.

<img src="https://user-images.githubusercontent.com/4311594/193402564-4610cc36-0cdb-40dd-ba05-78da572539c4.png"  height="300"/>

I think a new translation key might need to be added to keep the correct translation for the _"to update something"_-context.

**Comment by alisalahio** [comment]
Hi @lucasvdh We only use "an update about something." What's the correct translation for this?

**Comment by lucasvdh** [comment]
Then the correct translation would be: Update

https://www.vandale.nl/gratis-woordenboek/nederlands/betekenis/Update

**Comment by alisalahio** [comment]
Got you, just updated :D
